name: Run test.py and save CSV   # this is what you'll see in Actions tab

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run test.py
        run: python test.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v3
        with:
          name: btc-csv
          path: btc_ml_ma.csv
