name: Generate Chart and Save CSV

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      symbol:
        description: 'Trading symbol (e.g., BTCUSD)'
        required: true
        default: 'BTCUSD'
      interval:
        description: 'Time interval (e.g., 15m)'
        required: true
        default: '15m'
      days:
        description: 'Number of days'
        required: true
        default: '1'
        type: number

jobs:
  generate-chart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib mplfinance fastapi uvicorn requests 

    - name: Run chart generation script
      env:
        SYMBOL: ${{ github.event.inputs.symbol }}
        INTERVAL: ${{ github.event.inputs.interval }}
        DAYS: ${{ github.event.inputs.days }}
      run: |
        python -c "
        import subprocess
        import sys
        subprocess.run([sys.executable, '-m', 'uvicorn', 'dashboard:app', '--host', '0.0.0.0', '--port', '8000'], timeout=30)
        " &
        sleep 5
        curl -o chart.png "http://localhost:8000/chart?symbol=$SYMBOL&interval=$INTERVAL&days=$DAYS"
        pkill -f uvicorn

    - name: Find and save CSV files
      run: |
        # Find all CSV files created by the script
        CSV_FILES=$(find . -name "*.csv" -newer .github/workflows/generate-chart.yml 2>/dev/null || find . -name "*.csv")
        if [ -n "$CSV_FILES" ]; then
          echo "Found CSV files: $CSV_FILES"
          # Create artifacts directory
          mkdir -p artifacts
          # Copy CSV files to artifacts directory
          for file in $CSV_FILES; do
            cp "$file" artifacts/
          done
        else
          echo "No CSV files found"
        fi

    - name: Upload CSV artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chart-data-csv
        path: artifacts/*.csv
        if-no-files-found: warn

    - name: Upload chart image
      uses: actions/upload-artifact@v4
      with:
        name: chart-image
        path: chart.png
        if-no-files-found: warn

    - name: Commit and push CSV files (optional)
      run: |
        # Optional: Commit the CSV files to the repository
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any CSV files to commit
        if git status --porcelain | grep -E '\.csv$'; then
          git add *.csv
          git commit -m "Add generated CSV data for ${{ github.event.inputs.symbol }} ${{ github.event.inputs.interval }}"
          git push
        else
          echo "No CSV files to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
